<a href="https://colab.research.google.com/github/PabloDiosquez/Fundamentos_de_Programacion/blob/main/ProjectEuler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3,5,6 and 9. The sum of these multiples is 23. 

Find the sum of all multiples of 3 or 5 below 1000.

In [ ]:
def sum_of_multiples_below(x):
  sum = 0
  for i in range(x):
    if (not i % 3) or (not i % 5):
      sum += i
  
  return sum

sum_of_multiples_below(1000)

233168

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [15]:
def fibo(limit):
  first  = 1
  second = 2
  sum = 0
  while second < limit:
    if second % 2 == 0:
      sum += second
    
    next = first + second
    first = second
    second = next
  
  return sum 

fibo(4000000)

4613732

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [44]:
# from sympy import primefactors

# print(primefactors(600851475143))

def is_prime(n):
  d = 2
  while (n % d != 0) and (d <= n//2):
    d += 1
  
  if (n > 1) and (d > n//2):
    return True
  return False

def factors(n):
  factors = []
  div = 2
  while n > 1:
    if n % div == 0:
      factors.append(div)
      n = n // div
    div += 1
  return factors

max(list(filter(is_prime,[71, 839, 1471, 6857])))

6857